
service: awscloudfilestoragesystem
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  profile: serverlessUser
  region: eu-central-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
        - s3:*
      Resource: '*'

functions:
  getFile:
    handler: lambdas/getFile.get_file
    events: 
      - http:
          path: get-file/{bucket}/{filename}
          method: GET
          cors: true
  postFile:
    handler: lambdas/postFile.post_file
    events:
      - http:
          path: post-file/{bucket}/{filename}
          method: POST
          cors: true
          request:
            passThrought: WHEN_NO_MATCH
resources:
  Resources:
    BivujaBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: bivuja-bucket
  